spring:
  datasource:
    url: jdbc:h2:~/codes;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: codes
    password: 1234
  h2:
    console:
      enabled: true

